CREATE TABLE IF NOT EXISTS utilisateurs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    sexe VARCHAR(20) DEFAULT 'Homme',
    date_naissance DATE DEFAULT NULL,
    type_compte VARCHAR(50) DEFAULT 'citoyen',
    role VARCHAR(20) DEFAULT 'user',
    pays VARCHAR(100) DEFAULT 'Tunisie',
    ville VARCHAR(100) DEFAULT 'Tunis',
    email VARCHAR(190) NOT NULL UNIQUE,
    telephone VARCHAR(30) DEFAULT NULL,
    password VARCHAR(255) NOT NULL,
    cin VARCHAR(20) DEFAULT NULL UNIQUE,
    statut VARCHAR(30) DEFAULT 'en_attente',
    date_creation DATETIME DEFAULT CURRENT_TIMESTAMP,
    nom_organisation VARCHAR(190) DEFAULT NULL,
    profession VARCHAR(190) DEFAULT NULL,
    email_verifie TINYINT(1) DEFAULT 1,
    reset_token VARCHAR(255) DEFAULT NULL,
    reset_expires DATETIME DEFAULT NULL,
    verification_token VARCHAR(255) DEFAULT NULL,
    verification_expires DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
